/// <reference path="../../index.d.ts" />
declare namespace Api {
  export interface Prefs {
    accept_pms: "everyone" | "whitelisted";
    activity_relevant_ads: boolean;
    allow_clicktracking: boolean;
    beta: boolean;
    clickgadget: boolean;
    collapse_read_messages: boolean;
    compress: boolean;
    creddit_autorenew: boolean;
    default_comment_sort:
      | "confidence"
      | "top"
      | "new"
      | "controversial"
      | "old"
      | "random"
      | "qa"
      | "live";
    domain_details: boolean;
    email_chat_request: boolean;
    email_comment_reply: boolean;
    email_digests: boolean;
    email_messages: boolean;
    email_post_reply: boolean;
    email_private_message: boolean;
    email_unsubscribe_all: boolean;
    email_upvote_comment: boolean;
    email_upvote_post: boolean;
    email_user_new_follower: boolean;
    email_username_mention: boolean;
    enable_default_themes: boolean;
    feed_recommendations_enabled: boolean;
    g: Global;
    hide_ads: boolean;
    hide_downs: boolean;
    hide_from_robots: boolean;
    hide_ups: boolean;
    highlight_controversial: boolean;
    highlight_new_comments: boolean;
    ignore_suggested_sort: boolean;
    in_redesign_beta: boolean;
    label_nsfw: boolean;
    lang: string;
    legacy_search: boolean;
    live_orangereds: boolean;
    mark_messages_read: boolean;
    media: "on" | "off" | "subreddit";
    media_preview: "on" | "off" | "subreddit";
    min_comment_score: number;
    min_link_score: number;
    monitor_mentions: boolean;
    newwindow: boolean;
    nightmode: boolean;
    no_profanity: boolean;
    num_comments: number;
    numsites: number;
    organic: boolean;
    other_theme: string;
    over_18: boolean;
    private_feeds: boolean;
    profile_opt_out: boolean;
    public_votes: boolean;
    research: boolean;
    search_include_over_18: boolean;
    send_crosspost_messages: boolean;
    send_welcome_messages: boolean;
    show_flair: boolean;
    show_gold_expiration: boolean;
    show_link_flair: boolean;
    show_location_based_recommendations: boolean;
    show_presence: boolean;
    show_promote: boolean;
    show_stylesheets: boolean;
    show_trending: boolean;
    show_twitter: boolean;
    store_visits: boolean;
    survey_last_seen_time: number;
    theme_selector: string;
    third_party_data_personalized_ads: boolean;
    third_party_personalized_ads: boolean;
    third_party_site_data_personalized_ads: boolean;
    third_party_site_data_personalized_content: boolean;
    threaded_messages: boolean;
    threaded_modmail: boolean;
    top_karma_subreddits: boolean;
    use_global_defaults: boolean;
    video_autoplay: boolean;
  }

  type Global =
    | "GLOBAL"
    | "US"
    | "AR"
    | "AU"
    | "BG"
    | "CA"
    | "CL"
    | "CO"
    | "HR"
    | "CZ"
    | "FI"
    | "FR"
    | "DE"
    | "GR"
    | "HU"
    | "IS"
    | "IN"
    | "IE"
    | "IT"
    | "JP"
    | "MY"
    | "MX"
    | "NZ"
    | "PH"
    | "PL"
    | "PT"
    | "PR"
    | "RO"
    | "RS"
    | "SG"
    | "ES"
    | "SE"
    | "TW"
    | "TH"
    | "TR"
    | "GB"
    | "US_WA"
    | "US_DE"
    | "US_DC"
    | "US_WI"
    | "US_WV"
    | "US_HI"
    | "US_FL"
    | "US_WY"
    | "US_NH"
    | "US_NJ"
    | "US_NM"
    | "US_TX"
    | "US_LA"
    | "US_NC"
    | "US_ND"
    | "US_NE"
    | "US_TN"
    | "US_NY"
    | "US_PA"
    | "US_CA"
    | "US_NV"
    | "US_VA"
    | "US_CO"
    | "US_AK"
    | "US_AL"
    | "US_AR"
    | "US_VT"
    | "US_IL"
    | "US_GA"
    | "US_IN"
    | "US_IA"
    | "US_OK"
    | "US_AZ"
    | "US_ID"
    | "US_CT"
    | "US_ME"
    | "US_MD"
    | "US_MA"
    | "US_OH"
    | "US_UT"
    | "US_MO"
    | "US_MN"
    | "US_MI"
    | "US_RI"
    | "US_KS"
    | "US_MT"
    | "US_MS"
    | "US_SC"
    | "US_KY"
    | "US_OR"
    | "US_SD";
}
